SPOTIFY_AUTHORIZATION_BASE_URL = "https://accounts.spotify.com"
SPOTIFY_AUTHORIZE_URL = SPOTIFY_AUTHORIZATION_BASE_URL + "/authorize"
SPOTIFY_TOKEN_URL = SPOTIFY_AUTHORIZATION_BASE_URL + "/api/token"
SPOTIFY_API_BASE_URL = "https://api.spotify.com/v1"
